# Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/activiti_test
spring.datasource.username=postgres
spring.datasource.password=softwaredeveloper
spring.datasource.driver-class-name=org.postgresql.Driver

# Activiti configuration
spring.activiti.database-schema-update=true
spring.activiti.history-level=full
spring.activiti.db-history-used=true

spring.activiti.check-process-definitions=false
spring.activiti.process-definition-location-prefix=classpath:/disabled/

# Logging configuration
#logging.level.org.activiti=DEBUG
#logging.level.cv.nosi.igrp.runtime=DEBUG
