<?xml version="1.0" encoding="UTF-8"?>
<project
		xmlns="http://maven.apache.org/POM/4.0.0"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                            http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>cv.igrp.framework</groupId>
		<artifactId>igrp-process-studio-backend</artifactId>
		<version>0.1.0-beta.1</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>igrp-framework-process-management-integration-core</artifactId>
	<groupId>cv.igrp.framework.process.management.integration.core</groupId>
	<version>0.1.0-beta.1</version>

	<name>iGRP 3.0 Process Manager Core Integration</name>
	<description>iGRP 3.0 Process Manager Core Integration</description>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-autoconfigure</artifactId>
			<version>3.5.3</version>
		</dependency>
	</dependencies>

</project>
